# Generated by Django 5.2.7 on 2025-11-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
